sudo: required

language: android
jdk: oraclejdk8

notifications:
  email:
    recipients:
      - rudnev.vanya@gmail.com
    on_success: change
    on_failure: always

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

before_install:
  - yes | sdkmanager "platforms;android-27"

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

env:
 global:
 - ANDROID_API=27
 - ANDROID_BUILD_TOOLS=27.0.2

android:
  licenses:
    - android-sdk-preview-license-.+,,
    - android-sdk-license-.+,,
    - google-gdk-license-.+
  components:
    - tools
    - tools # Running this twice get's the latest build tools
    - platform-tools
    - android-${ANDROID_API}
    - build-tools-${ANDROID_BUILD_TOOLS}
    - extra-android-m2repository,
    - extra-google-m2repository,
    - extra-android-support,
    - extra-google-google_play_services

script:
  - ./gradlew test